### PR TITLE
🔢  Add fuzzing to close #19

### LINKED ISSUE #19: 🧪 Add fuzzing to test cases
Foundry has cool tools around 'fuzzing' testcases by creating function params, which will simulate many runs
https://github.com/gakonst/foundry/tree/master/forge#fuzzing-go-beyond-unit-testing

### PR DESCRIPTION
**Pull request by zfaizal2**
TBH just trying this out since it seems cool, not sure if this is the best way to do it. Just removed some hardcoded variables and replaced them as function params. Left the other test cases there just in case. How do we check what these tests are fuzzing?
image

### CODE REVIEW

**Comment by alecchendev** [comment]
when it gives mu and runs data afterwards I'm pretty sure that's for fuzzing so I think you're doing it all right

**Review by alecchendev — APPROVED** [review]
If you actually merge I think you can just keep the fuzzing ones and delete the previous and rename them to just normal without "withFuzzing" - also fuzzing might not be totally necessary for some of them so if you want to keep or get rid of some of the fuzzing ones too its all good with me

**Comment by zfaizal2** [comment]
OK, fuzzing is probably not necessary for AddOwner since they're just addresses, so I'll remove that -- and I thought it would be useful to keep with and without fuzzing for now so we can test specific cases while also having a separate case for fuzzing

**Comment by alecchendev** [comment]
👍

**Pull request merged**
